#!/bin/bash

. rec-command

function monitor() {
	while :
	do
		cpuusage1=$(((RANDOM % 100) + 1))
		cpuusage2=$(((RANDOM % 100) + 1))
		memusage1=$(((RANDOM % 100) + 1))
		memusage2=$(((RANDOM % 100) + 1))
		rec 'LocationA' 'CpuUsage' $cpuusage1 'xxxxx@gmail.com' 'Test'
		rec 'LocationB' 'CpuUsage' $cpuusage2 'xxxxx@gmail.com' 'Test'
		rec 'LocationA' 'MemUsage' $memusage1 'xxxxx@gmail.com' 'Test'
		rec 'LocationB' 'MemUsage' $memusage2 'xxxxx@gmail.com' 'Test'
		sleep 5
	done
}

monitor
