#!/bin/bash

# this script is used for sending result of dscript
# > USAGE: ./rec-command


## CONST DATA
jsonrpc='\"2.0\"'
method='\"rawDataRecord\"'
id='0' #FIXME
default_rec_server_url='http://live.assure-it.org/rec/api/1.0/'


## API
# void rec(String type, String, data, String context);
function rec() {
	local location='\"\"'
	local type='\"'$1'\"'
	local data=$2
	local timestamp='\"\"'
	local context='\"'$3'\"'
	local params='\{location:'$location',type:'$type',data:'$data',timestamp:'$timestamp',context:'$context'}'
	local request='\{jsonrpc:'$jsonrpc',method:'$method',id:'$id',params:'$params'\}'

	if [ $# -eq 3 ]; then
		echo $request
		curl -H 'Content-Type=application/json' -d $request $default_rec_server_url
	else
		exit 1
	fi
}
